// <auto-generated />
using System;
using CvApp.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CvApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230926150027_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CvApp.Data.Entities.CertificateEntity", b =>
                {
                    b.Property<int>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CertificateCompany")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CertificateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CertificateDescription")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CertificateName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("fileName")
                        .HasColumnType("longtext");

                    b.Property<string>("filePath")
                        .HasColumnType("longtext");

                    b.HasKey("CertificateId");

                    b.HasIndex("PersonId");

                    b.ToTable("CertificatesTable");
                });

            modelBuilder.Entity("CvApp.Data.Entities.EducationEntity", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("DegreeNote")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EducationDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("EducationLanguage")
                        .HasColumnType("longtext");

                    b.Property<string>("EducationType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FacultyName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("PersonEntityId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("fileName")
                        .HasColumnType("longtext");

                    b.Property<string>("filePath")
                        .HasColumnType("longtext");

                    b.HasKey("EducationId");

                    b.HasIndex("PersonEntityId");

                    b.ToTable("EducationsTable");
                });

            modelBuilder.Entity("CvApp.Data.Entities.FactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .HasColumnType("longtext");

                    b.Property<int?>("PropertyStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("FactsTable");
                });

            modelBuilder.Entity("CvApp.Data.Entities.JobInformationEntity", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompanyCreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("longtext");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyLocation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CompanySector")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("IsContinue")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WorkingMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("fileName")
                        .HasColumnType("longtext");

                    b.Property<string>("filePath")
                        .HasColumnType("longtext");

                    b.HasKey("JobId");

                    b.HasIndex("PersonId");

                    b.ToTable("JobInformationsTable");
                });

            modelBuilder.Entity("CvApp.Data.Entities.KnownProgramEntity", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("ProgramDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("ProgramName")
                        .HasColumnType("longtext");

                    b.Property<string>("fileName")
                        .HasColumnType("longtext");

                    b.Property<string>("filePath")
                        .HasColumnType("longtext");

                    b.Property<int?>("programStock")
                        .HasColumnType("int");

                    b.HasKey("ProgramId");

                    b.HasIndex("PersonId");

                    b.ToTable("KnownProgramsTable");
                });

            modelBuilder.Entity("CvApp.Data.Entities.LanguageEntity", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("LanguageCount")
                        .HasColumnType("int");

                    b.Property<string>("LanguageDescription")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LanguageLevel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("fileName")
                        .HasColumnType("longtext");

                    b.Property<string>("filePath")
                        .HasColumnType("longtext");

                    b.HasKey("LanguageId");

                    b.HasIndex("PersonId");

                    b.ToTable("LanguagesTable");
                });

            modelBuilder.Entity("CvApp.Data.Entities.MessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("SenderMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("SenderName")
                        .HasColumnType("longtext");

                    b.Property<string>("SenderSubject")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("MessagesTable");
                });

            modelBuilder.Entity("CvApp.Data.Entities.PersonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PersonsTable");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("CvApp.Data.Entities.ReferanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("ReferanceDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferanceName")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferanceTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("fileName")
                        .HasColumnType("longtext");

                    b.Property<string>("filePath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("ReferancesTable");
                });

            modelBuilder.Entity("CvApp.Data.Entities.ServiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("fileName")
                        .HasColumnType("longtext");

                    b.Property<string>("filePath")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("ServicesTable");
                });

            modelBuilder.Entity("CvApp.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("BirtDay")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FacebookLink")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Hobies")
                        .HasColumnType("longtext");

                    b.Property<string>("InstagramLınk")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LinkedinLink")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<bool?>("MSwasDone")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("PasswordConfirm")
                        .HasColumnType("longtext");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SkypeLınk")
                        .HasColumnType("longtext");

                    b.Property<string>("TwitterLink")
                        .HasColumnType("longtext");

                    b.Property<string>("UK")
                        .HasColumnType("longtext");

                    b.Property<int?>("UserCount")
                        .HasColumnType("int");

                    b.Property<string>("UserDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("fileName")
                        .HasColumnType("longtext");

                    b.Property<string>("filePath")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("PersonId");

                    b.ToTable("UsersTable");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Adress = "Sample Address",
                            BirtDay = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2023, 9, 26, 18, 0, 26, 992, DateTimeKind.Local).AddTicks(7594),
                            Email = "john@example.com",
                            FacebookLink = "https://facebook.com/johndoe",
                            FirstName = "John",
                            Gender = "Male",
                            Hobies = "Sample Hobbies",
                            InstagramLınk = "https://instagram.com/johndoe",
                            LastName = "Doe",
                            LinkedinLink = "https://linkedin.com/johndoe",
                            Location = "Sample Location",
                            MSwasDone = true,
                            Password = "123456",
                            PasswordConfirm = "",
                            PersonId = 1,
                            PhoneNumber = "1234567890",
                            Roles = "User",
                            SkypeLınk = "https://skype.com/johndoe",
                            TwitterLink = "https://twitter.com/johndoe",
                            UK = "",
                            UserDescription = "Sample description",
                            UserName = "johndoe",
                            fileName = "1684652602676.jpg@",
                            filePath = ""
                        });
                });

            modelBuilder.Entity("CvApp.Data.Entities.CertificateEntity", b =>
                {
                    b.HasOne("CvApp.Data.Entities.PersonEntity", "Person")
                        .WithMany("Certificates")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CvApp.Data.Entities.EducationEntity", b =>
                {
                    b.HasOne("CvApp.Data.Entities.PersonEntity", null)
                        .WithMany("Educations")
                        .HasForeignKey("PersonEntityId");
                });

            modelBuilder.Entity("CvApp.Data.Entities.FactEntity", b =>
                {
                    b.HasOne("CvApp.Data.Entities.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CvApp.Data.Entities.JobInformationEntity", b =>
                {
                    b.HasOne("CvApp.Data.Entities.PersonEntity", "Person")
                        .WithMany("JobInformation")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CvApp.Data.Entities.KnownProgramEntity", b =>
                {
                    b.HasOne("CvApp.Data.Entities.PersonEntity", "Person")
                        .WithMany("KnownPrograms")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CvApp.Data.Entities.LanguageEntity", b =>
                {
                    b.HasOne("CvApp.Data.Entities.PersonEntity", "Person")
                        .WithMany("Languages")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CvApp.Data.Entities.MessageEntity", b =>
                {
                    b.HasOne("CvApp.Data.Entities.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CvApp.Data.Entities.ReferanceEntity", b =>
                {
                    b.HasOne("CvApp.Data.Entities.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CvApp.Data.Entities.ServiceEntity", b =>
                {
                    b.HasOne("CvApp.Data.Entities.PersonEntity", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CvApp.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("CvApp.Data.Entities.PersonEntity", "Person")
                        .WithMany("Users")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CvApp.Data.Entities.PersonEntity", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Educations");

                    b.Navigation("JobInformation");

                    b.Navigation("KnownPrograms");

                    b.Navigation("Languages");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
